/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed nth term, find the sum of the even-valued terms.
*/


// function fiboEvenSum(n) {
//   var fib = [], i, j, sum = 0;
//   fib[0] = 1;
//   fib[1] = 2;
//   for(i = 2; i <= n; i += 1) {
//     fib[i] = fib[i - 2] + fib[i - 1];
//   }
//   for(j = 0; j < fib.length; j += 1) {
//     if(fib[j] % 2 === 0) sum += fib[j];
//   }
//   return sum;
// }
//
// fiboEvenSum(10);